"""Build notebooks/ev02_excavator_battery_diagnostic_report.ipynb"""
import json
from pathlib import Path


def code_cell(source):
    return {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": source}


def md_cell(source):
    return {"cell_type": "markdown", "metadata": {}, "source": source}


cells = [
    md_cell(
        "# EV02 Battery Health Diagnostic Report\n"
        "## Electrified Excavator — Battery Pack Analysis\n\n---\n\n"
        "**Vehicle:** EV02  \n"
        "**Analysis Window:** 2026-01-22 → 2026-05-14  \n"
        "**Data:** Silver (1 Hz telemetry) + Cell gold features merged into master dataset  \n"
        "**Purpose:** Identify battery health patterns, module-level anomalies, and degraded cells\n\n---\n\n"
        "### What this notebook covers\n"
        "1. Operating profile (active hours, SOC range, current distribution)\n"
        "2. Battery pack health (cell spread, pack voltage std, temperature range)\n"
        "3. Module-by-module comparison (thermal dominance, voltage ranking)\n"
        "4. Which module runs hottest and why\n"
        "5. Degraded cell analysis (worst cell identity, module breakdown)\n"
        "6. When does imbalance get worse? (SOC, current, operating regime)\n"
        "7. Worst operating condition (low SOC + heavy load combination)\n"
        "8. Trip-level analysis (most stressed sessions)\n"
        "9. Executive summary dashboard"
    ),

    md_cell("## Setup\n\n**What this does:** Imports libraries and configures plotting style."),

    code_cell(
        "import pandas as pd\n"
        "import numpy as np\n"
        "import matplotlib.pyplot as plt\n"
        "import matplotlib.gridspec as gridspec\n"
        "import warnings\n"
        "from pathlib import Path\n\n"
        "warnings.filterwarnings('ignore')\n\n"
        "plt.rcParams.update({\n"
        "    'figure.facecolor': 'white',\n"
        "    'axes.facecolor': '#f8f9fa',\n"
        "    'axes.grid': True,\n"
        "    'grid.alpha': 0.4,\n"
        "    'axes.spines.top': False,\n"
        "    'axes.spines.right': False,\n"
        "    'font.size': 11,\n"
        "    'axes.titlesize': 13,\n"
        "    'axes.titleweight': 'bold',\n"
        "    'figure.titlesize': 15,\n"
        "    'figure.titleweight': 'bold',\n"
        "})\n\n"
        "import os\n"
        "# Ensure working directory is the project root regardless of where Jupyter starts\n"
        "_nb_dir = Path('__file__').parent if '__file__' in dir() else Path.cwd()\n"
        "_project_root = Path('/Users/rhythmparashar/Desktop/ev-predictive-analytics')\n"
        "if _project_root.exists():\n"
        "    os.chdir(_project_root)\n\n"
        "MASTER = Path('data/analysis/master')\n"
        "VEHICLE_ID = 'EV02'\n"
        "COLORS = ['#2196F3', '#FF5722', '#4CAF50', '#FF9800', '#9C27B0']\n"
        "MODULE_COLORS = {1: '#E53935', 2: '#1E88E5', 3: '#43A047', 4: '#FB8C00', 5: '#8E24AA'}\n\n"
        "print('Setup complete. Ready to load data.')"
    ),

    md_cell(
        "---\n## Section 1 — Load Data\n\n"
        "**What this does:** Loads all master dataset partitions into a single dataframe.  \n"
        "**What to look for:** Total rows, date range, and that all 5 modules are present."
    ),

    code_cell(
        "dfs = []\n"
        "for p in sorted(MASTER.glob(f'dt=*/vehicle_id={VEHICLE_ID}.parquet')):\n"
        "    dfs.append(pd.read_parquet(p))\n\n"
        "df = pd.concat(dfs, ignore_index=True)\n"
        "df['timestamp'] = pd.to_datetime(df['timestamp'])\n"
        "df['date'] = df['timestamp'].dt.date.astype(str)\n\n"
        "# Remove flatline artifact rows (cell_quality_flag bit 32)\n"
        "df_clean = df[(df['cell_quality_flag'] & 32) == 0].copy()\n\n"
        "# Derive hottest and lowest voltage module numbers\n"
        "df_clean['hottest_module'] = pd.to_numeric(\n"
        "    df_clean['hottest_module_id'].astype(str).str.extract(r'(\\d+)')[0], errors='coerce'\n"
        ")\n"
        "mod_mean_cols = [f'module_{i}_voltage_mean' for i in range(1, 6)]\n"
        "df_clean['lowest_voltage_module'] = df_clean[mod_mean_cols].idxmin(axis=1).str.extract(r'(\\d+)').astype(float)\n\n"
        "print(f'Total rows loaded:        {len(df):,}')\n"
        "print(f'Clean rows (no flatline): {len(df_clean):,}')\n"
        "print(f'Flatline rows removed:    {len(df) - len(df_clean):,}')\n"
        "print(f'Date range:               {df_clean[\"date\"].min()} → {df_clean[\"date\"].max()}')\n"
        "print(f'Unique dates:             {df_clean[\"date\"].nunique()}')\n"
        "print(f'Unique trips:             {df_clean[\"trip_id\"].nunique():,}')\n"
        "print(f'Columns:                  {len(df_clean.columns)}')"
    ),

    md_cell(
        "---\n## Section 2 — Operating Profile\n\n"
        "**What this does:** Builds a daily activity profile.\n"
        "**What to look for:** Active hours per day, SOC working range, current distribution."
    ),

    code_cell(
        "daily = df_clean.groupby('date').agg(\n"
        "    total_rows=('timestamp', 'count'),\n"
        "    active_rows=('abs_current_a', lambda x: (x > 10).sum()),\n"
        "    soc_max=('soc_pct', 'max'),\n"
        "    soc_min=('soc_pct', 'min'),\n"
        "    soc_mean=('soc_pct', 'mean'),\n"
        "    max_current=('battery_current_a', 'max'),\n"
        "    mean_current=('abs_current_a', 'mean'),\n"
        "    max_temp=('avg_battery_temp_c', 'max'),\n"
        ").reset_index()\n\n"
        "daily['total_hours'] = (daily['total_rows'] / 3600).round(2)\n"
        "daily['active_hours'] = (daily['active_rows'] / 3600).round(2)\n"
        "daily['idle_hours'] = daily['total_hours'] - daily['active_hours']\n"
        "daily['active_pct'] = (daily['active_rows'] / daily['total_rows'] * 100).round(1)\n"
        "daily['soc_swing'] = daily['soc_max'] - daily['soc_min']\n\n"
        "print('=== DAILY OPERATING SUMMARY ===')\n"
        "print(f\"Average active hours per day:  {daily['active_hours'].mean():.1f}h\")\n"
        "print(f\"Average total hours per day:   {daily['total_hours'].mean():.1f}h\")\n"
        "print(f\"Average active percentage:     {daily['active_pct'].mean():.1f}%\")\n"
        "print(f\"Average daily SOC swing:       {daily['soc_swing'].mean():.1f}%\")\n"
        "print(f\"Median SOC during operation:   {df_clean['soc_pct'].median():.0f}%\")\n"
        "print(f\"Max recorded current:          {df_clean['battery_current_a'].max():.0f}A\")\n"
        "print(f\"Typical working current (p50): {df_clean[df_clean['abs_current_a']>10]['abs_current_a'].median():.0f}A\")"
    ),

    code_cell(
        "fig, axes = plt.subplots(2, 2, figsize=(16, 10))\n"
        "fig.suptitle(f'EV02 Operating Profile — {df_clean[\"date\"].min()} to {df_clean[\"date\"].max()}')\n"
        "dates = pd.to_datetime(daily['date'])\n\n"
        "ax = axes[0, 0]\n"
        "ax.bar(dates, daily['active_hours'], color='#2196F3', alpha=0.85, label='Active (>10A)')\n"
        "ax.bar(dates, daily['idle_hours'], bottom=daily['active_hours'], color='#B0BEC5', alpha=0.7, label='Idle')\n"
        "ax.axhline(daily['active_hours'].mean(), color='#1565C0', linestyle='--', linewidth=1.5)\n"
        "ax.set_title('Daily Active vs Idle Hours'); ax.set_ylabel('Hours'); ax.legend()\n"
        "ax.tick_params(axis='x', rotation=45)\n\n"
        "ax = axes[0, 1]\n"
        "ax.fill_between(dates, daily['soc_min'], daily['soc_max'], alpha=0.3, color='#4CAF50', label='SOC range')\n"
        "ax.plot(dates, daily['soc_mean'], color='#2E7D32', linewidth=2, label='Mean SOC')\n"
        "ax.plot(dates, daily['soc_min'], color='#E53935', linewidth=1.5, linestyle='--', label='Min SOC')\n"
        "ax.set_title('Daily SOC Range'); ax.set_ylabel('SOC (%)'); ax.set_ylim(0, 105)\n"
        "ax.legend(fontsize=9); ax.tick_params(axis='x', rotation=45)\n\n"
        "ax = axes[1, 0]\n"
        "ax.hist(df_clean['soc_pct'].dropna(), bins=50, color='#4CAF50', alpha=0.8, edgecolor='white')\n"
        "ax.axvline(df_clean['soc_pct'].median(), color='#1B5E20', linestyle='--', linewidth=2,\n"
        "           label=f\"Median: {df_clean['soc_pct'].median():.0f}%\")\n"
        "ax.axvline(20, color='#E53935', linestyle=':', linewidth=2, label='Low SOC (20%)')\n"
        "ax.set_title('SOC Distribution'); ax.set_xlabel('SOC (%)'); ax.set_ylabel('Count'); ax.legend()\n\n"
        "ax = axes[1, 1]\n"
        "discharge = df_clean[df_clean['operating_regime'].isin(['light_discharge', 'heavy_discharge'])]\n"
        "ax.hist(discharge['battery_current_a'].dropna(), bins=60, color='#FF5722', alpha=0.8, edgecolor='white')\n"
        "ax.axvline(discharge['battery_current_a'].median(), color='#BF360C', linestyle='--', linewidth=2,\n"
        "           label=f\"Median: {discharge['battery_current_a'].median():.0f}A\")\n"
        "ax.axvline(100, color='#E53935', linestyle=':', linewidth=2, label='Heavy work (100A)')\n"
        "ax.set_title('Current Distribution (Discharge)'); ax.set_xlabel('Current (A)'); ax.legend()\n\n"
        "plt.tight_layout()\n"
        "Path('outputs/ev02').mkdir(parents=True, exist_ok=True)\n"
        "plt.savefig('outputs/ev02/01_operating_profile.png', dpi=150, bbox_inches='tight')\n"
        "plt.show()"
    ),

    md_cell(
        "---\n## Section 3 — Battery Pack Health Overview\n\n"
        "**What this does:** Shows pack-level health metrics over time.\n"
        "**What to look for:** Cell spread trend vs 90mV warn / 130mV alert thresholds."
    ),

    code_cell(
        "daily_health = df_clean.groupby('date').agg(\n"
        "    mean_spread=('cell_spread_v', 'mean'),\n"
        "    p95_spread=('cell_spread_v', lambda x: x.quantile(0.95)),\n"
        "    max_spread=('cell_spread_v', 'max'),\n"
        "    mean_temp_range=('pack_temp_range', 'mean'),\n"
        "    p95_temp_range=('pack_temp_range', lambda x: x.quantile(0.95)),\n"
        "    mean_pack_v_std=('pack_voltage_std', 'mean'),\n"
        "    n=('cell_spread_v', 'count'),\n"
        ").reset_index()\n"
        "dates = pd.to_datetime(daily_health['date'])\n\n"
        "print('=== PACK HEALTH SUMMARY ===')\n"
        "print(f\"Overall mean cell spread:      {df_clean['cell_spread_v'].mean()*1000:.1f} mV\")\n"
        "print(f\"Overall p95 cell spread:       {df_clean['cell_spread_v'].quantile(0.95)*1000:.1f} mV\")\n"
        "print(f\"Imbalance threshold (warn):    90 mV\")\n"
        "print(f\"Imbalance threshold (alert):   130 mV\")\n"
        "print(f\"% time above warn threshold:   {(df_clean['cell_spread_v'] > 0.09).mean()*100:.1f}%\")\n"
        "print(f\"% time above alert threshold:  {(df_clean['cell_spread_v'] > 0.13).mean()*100:.1f}%\")\n"
        "print(f\"Mean pack temp range:          {df_clean['pack_temp_range'].mean():.1f}°C\")\n"
        "print(f\"Max pack temp range observed:  {df_clean['pack_temp_range'].max():.0f}°C\")"
    ),

    code_cell(
        "fig, axes = plt.subplots(3, 1, figsize=(16, 13))\n"
        "fig.suptitle('EV02 Battery Pack Health — Daily Trends')\n\n"
        "ax = axes[0]\n"
        "ax.fill_between(dates, daily_health['mean_spread']*1000, daily_health['p95_spread']*1000,\n"
        "                alpha=0.2, color='#2196F3', label='Mean to p95 band')\n"
        "ax.plot(dates, daily_health['mean_spread']*1000, color='#1565C0', linewidth=2, marker='o', markersize=4, label='Mean spread')\n"
        "ax.plot(dates, daily_health['p95_spread']*1000, color='#2196F3', linewidth=1.5, linestyle='--', label='p95 spread')\n"
        "ax.axhline(90, color='#FF9800', linestyle='--', linewidth=2, label='Warn (90mV)')\n"
        "ax.axhline(130, color='#E53935', linestyle='--', linewidth=2, label='Alert (130mV)')\n"
        "ax.set_title('Daily Cell Voltage Spread (mV) — Lower is Healthier')\n"
        "ax.set_ylabel('Cell Spread (mV)'); ax.legend(fontsize=9); ax.tick_params(axis='x', rotation=45)\n\n"
        "ax = axes[1]\n"
        "ax.plot(dates, daily_health['mean_pack_v_std']*1000, color='#9C27B0', linewidth=2, marker='o', markersize=4)\n"
        "ax.fill_between(dates, 0, daily_health['mean_pack_v_std']*1000, alpha=0.15, color='#9C27B0')\n"
        "ax.set_title('Daily Pack Voltage Standard Deviation (mV)')\n"
        "ax.set_ylabel('Pack Voltage Std (mV)'); ax.tick_params(axis='x', rotation=45)\n\n"
        "ax = axes[2]\n"
        "ax.fill_between(dates, daily_health['mean_temp_range'], daily_health['p95_temp_range'],\n"
        "                alpha=0.2, color='#FF5722', label='Mean to p95 band')\n"
        "ax.plot(dates, daily_health['mean_temp_range'], color='#BF360C', linewidth=2, marker='o', markersize=4, label='Mean temp range')\n"
        "ax.plot(dates, daily_health['p95_temp_range'], color='#FF5722', linewidth=1.5, linestyle='--', label='p95 temp range')\n"
        "ax.axhline(15, color='#FF9800', linestyle='--', linewidth=2, label='Hotspot threshold (15°C)')\n"
        "ax.set_title('Daily Pack Temperature Range (°C)')\n"
        "ax.set_ylabel('Temperature Range (°C)'); ax.legend(fontsize=9); ax.tick_params(axis='x', rotation=45)\n\n"
        "plt.tight_layout()\n"
        "plt.savefig('outputs/ev02/02_pack_health_daily.png', dpi=150, bbox_inches='tight')\n"
        "plt.show()"
    ),

    md_cell(
        "---\n## Section 4 — Module-by-Module Comparison\n\n"
        "**What this does:** Compares all 5 modules across temperature, voltage, and imbalance metrics.\n"
        "**What to look for:** Which module is consistently hottest and/or lowest voltage."
    ),

    code_cell(
        "module_stats = []\n"
        "for i in range(1, 6):\n"
        "    module_stats.append({\n"
        "        'Module': f'Module {i}',\n"
        "        'Mean Voltage (V)': df_clean[f'module_{i}_voltage_mean'].mean(),\n"
        "        'Voltage Std (mV)': df_clean[f'module_{i}_voltage_std'].mean() * 1000,\n"
        "        'Voltage Range (mV)': df_clean[f'module_{i}_voltage_range'].mean() * 1000,\n"
        "        'Mean Temp (°C)': df_clean[f'module_{i}_temp_mean'].mean(),\n"
        "        'Temp Range (°C)': df_clean[f'module_{i}_temp_range'].mean(),\n"
        "        'Hottest (% time)': (df_clean['hottest_module'] == i).mean() * 100,\n"
        "        'Lowest Voltage (% time)': (df_clean['lowest_voltage_module'] == i).mean() * 100,\n"
        "    })\n\n"
        "module_df = pd.DataFrame(module_stats)\n"
        "print('=== MODULE COMPARISON TABLE ===')\n"
        "print(module_df.round(3).to_string(index=False))\n"
        "hot_mod = int(module_df['Hottest (% time)'].idxmax()) + 1\n"
        "low_mod = int(module_df['Lowest Voltage (% time)'].idxmax()) + 1\n"
        "print(f'\\n→ Hottest module: Module {hot_mod} ({module_df[\"Hottest (% time)\"].max():.1f}% of time)')\n"
        "print(f'→ Lowest voltage module: Module {low_mod} ({module_df[\"Lowest Voltage (% time)\"].max():.1f}% of time)')"
    ),

    code_cell(
        "fig, axes = plt.subplots(2, 3, figsize=(18, 11))\n"
        "fig.suptitle('EV02 Module Comparison — All 5 Modules vs Each Other')\n"
        "modules = [f'Module {i}' for i in range(1, 6)]\n"
        "colors = [MODULE_COLORS[i] for i in range(1, 6)]\n\n"
        "ax = axes[0, 0]\n"
        "vals = [module_df.loc[i, 'Hottest (% time)'] for i in range(5)]\n"
        "bars = ax.bar(modules, vals, color=colors, edgecolor='white', linewidth=1.5)\n"
        "ax.set_title('% Time Each Module is\\nthe Hottest in the Pack'); ax.set_ylabel('% of all rows')\n"
        "for bar, val in zip(bars, vals):\n"
        "    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.5,\n"
        "            f'{val:.1f}%', ha='center', va='bottom', fontweight='bold', fontsize=10)\n"
        "ax.set_ylim(0, max(vals) * 1.2)\n\n"
        "ax = axes[0, 1]\n"
        "vals = [module_df.loc[i, 'Lowest Voltage (% time)'] for i in range(5)]\n"
        "bars = ax.bar(modules, vals, color=colors, edgecolor='white', linewidth=1.5)\n"
        "ax.set_title('% Time Each Module has the\\nLowest Voltage in the Pack'); ax.set_ylabel('% of all rows')\n"
        "for bar, val in zip(bars, vals):\n"
        "    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.3,\n"
        "            f'{val:.1f}%', ha='center', va='bottom', fontweight='bold', fontsize=10)\n\n"
        "ax = axes[0, 2]\n"
        "vals = [module_df.loc[i, 'Mean Temp (°C)'] for i in range(5)]\n"
        "bars = ax.bar(modules, vals, color=colors, edgecolor='white', linewidth=1.5)\n"
        "ax.set_title('Mean Operating Temperature per Module (°C)'); ax.set_ylabel('Temperature (°C)')\n"
        "ax.set_ylim(min(vals) - 1, max(vals) + 1)\n"
        "for bar, val in zip(bars, vals):\n"
        "    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.02,\n"
        "            f'{val:.2f}°C', ha='center', va='bottom', fontsize=9)\n\n"
        "ax = axes[1, 0]\n"
        "vals = [module_df.loc[i, 'Mean Voltage (V)'] for i in range(5)]\n"
        "bars = ax.bar(modules, vals, color=colors, edgecolor='white', linewidth=1.5)\n"
        "ax.set_title('Mean Cell Voltage per Module (V)\\nLower = Weaker cells'); ax.set_ylabel('Voltage (V)')\n"
        "ax.set_ylim(min(vals) - 0.0005, max(vals) + 0.0005)\n"
        "for bar, val in zip(bars, vals):\n"
        "    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.00005,\n"
        "            f'{val:.5f}V', ha='center', va='bottom', fontsize=8)\n\n"
        "ax = axes[1, 1]\n"
        "vals = [module_df.loc[i, 'Voltage Range (mV)'] for i in range(5)]\n"
        "bars = ax.bar(modules, vals, color=colors, edgecolor='white', linewidth=1.5)\n"
        "ax.set_title('Mean Internal Voltage Range per Module (mV)\\nHigher = More cell imbalance')\n"
        "ax.set_ylabel('Voltage Range (mV)')\n"
        "for bar, val in zip(bars, vals):\n"
        "    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.1,\n"
        "            f'{val:.1f}mV', ha='center', va='bottom', fontsize=9)\n\n"
        "ax = axes[1, 2]\n"
        "vals = [module_df.loc[i, 'Temp Range (°C)'] for i in range(5)]\n"
        "bars = ax.bar(modules, vals, color=colors, edgecolor='white', linewidth=1.5)\n"
        "ax.set_title('Mean Temperature Range per Module (°C)\\nHigher = More thermal spread')\n"
        "ax.set_ylabel('Temp Range (°C)')\n"
        "for bar, val in zip(bars, vals):\n"
        "    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.02,\n"
        "            f'{val:.1f}°C', ha='center', va='bottom', fontsize=9)\n\n"
        "plt.tight_layout()\n"
        "plt.savefig('outputs/ev02/03_module_comparison.png', dpi=150, bbox_inches='tight')\n"
        "plt.show()"
    ),

    md_cell(
        "---\n## Section 5 — Dominant Module Deep Dive\n\n"
        "**What this does:** Deep-dives into the hottest/weakest module.\n"
        "**What to look for:** Does the dominance hold across all SOC bands and current levels?"
    ),

    code_cell(
        "# Module dominance by SOC band\n"
        "soc_mod = df_clean.assign(\n"
        "    mod_hot=(df_clean['hottest_module'] == hot_mod),\n"
        "    mod_low=(df_clean['lowest_voltage_module'] == hot_mod)\n"
        ").groupby('soc_band', observed=False).agg(\n"
        "    pct_mod_hot=('mod_hot', 'mean'),\n"
        "    pct_mod_low=('mod_low', 'mean'),\n"
        "    mean_spread=('cell_spread_v', 'mean'),\n"
        "    n=('cell_spread_v', 'size')\n"
        ").reset_index()\n\n"
        "df_clean['current_bin'] = pd.cut(df_clean['abs_current_a'],\n"
        "                                  bins=[0, 10, 50, 100, 150, float('inf')],\n"
        "                                  labels=['Idle (<10A)', 'Low (10-50A)', 'Med (50-100A)', 'High (100-150A)', 'Max (>150A)'],\n"
        "                                  include_lowest=True)\n"
        "cur_mod = df_clean.assign(\n"
        "    mod_hot=(df_clean['hottest_module'] == hot_mod),\n"
        "    mod_low=(df_clean['lowest_voltage_module'] == hot_mod)\n"
        ").groupby('current_bin', observed=False).agg(\n"
        "    pct_mod_hot=('mod_hot', 'mean'),\n"
        "    pct_mod_low=('mod_low', 'mean'),\n"
        "    mean_spread=('cell_spread_v', 'mean'),\n"
        "    n=('cell_spread_v', 'size')\n"
        ").reset_index()\n\n"
        "print(f'Module {hot_mod} dominance by SOC band:')\n"
        "print(soc_mod[['soc_band', 'pct_mod_hot', 'pct_mod_low', 'mean_spread', 'n']].round(3).to_string(index=False))\n"
        "print(f'\\nModule {hot_mod} dominance by current level:')\n"
        "print(cur_mod[['current_bin', 'pct_mod_hot', 'pct_mod_low', 'mean_spread', 'n']].round(3).to_string(index=False))"
    ),

    code_cell(
        "fig, axes = plt.subplots(2, 2, figsize=(16, 12))\n"
        "fig.suptitle(f'Module {hot_mod} — Thermal and Voltage Dominance Analysis')\n"
        "soc_labels = soc_mod['soc_band'].astype(str).tolist()\n"
        "cur_labels = cur_mod['current_bin'].astype(str).tolist()\n"
        "x = np.arange(len(soc_labels)); xc = np.arange(len(cur_labels))\n\n"
        "ax = axes[0, 0]\n"
        "bars = ax.bar(x, soc_mod['pct_mod_hot']*100, color=MODULE_COLORS[hot_mod], alpha=0.85, edgecolor='white')\n"
        "ax.axhline(20, color='gray', linestyle=':', linewidth=1.5, label='Expected if uniform (20%)')\n"
        "ax.set_xticks(x); ax.set_xticklabels(soc_labels)\n"
        "ax.set_title(f'% Time Module {hot_mod} is Hottest by SOC Band')\n"
        "ax.set_ylabel('% of rows'); ax.set_ylim(0, 100); ax.legend()\n"
        "for bar, val in zip(bars, soc_mod['pct_mod_hot']):\n"
        "    ax.text(bar.get_x()+bar.get_width()/2, bar.get_height()+1,\n"
        "            f'{val*100:.0f}%', ha='center', va='bottom', fontweight='bold')\n\n"
        "ax = axes[0, 1]\n"
        "bars = ax.bar(xc, cur_mod['pct_mod_hot']*100, color=MODULE_COLORS[hot_mod], alpha=0.85, edgecolor='white')\n"
        "ax.axhline(20, color='gray', linestyle=':', linewidth=1.5, label='Expected if uniform (20%)')\n"
        "ax.set_xticks(xc); ax.set_xticklabels(cur_labels, rotation=20)\n"
        "ax.set_title(f'% Time Module {hot_mod} is Hottest by Current Level')\n"
        "ax.set_ylabel('% of rows'); ax.set_ylim(0, 100); ax.legend()\n"
        "for bar, val in zip(bars, cur_mod['pct_mod_hot']):\n"
        "    ax.text(bar.get_x()+bar.get_width()/2, bar.get_height()+1,\n"
        "            f'{val*100:.0f}%', ha='center', va='bottom', fontweight='bold')\n\n"
        "ax = axes[1, 0]\n"
        "m_low = df_clean[df_clean['lowest_voltage_module']==hot_mod]['cell_spread_v'].dropna()*1000\n"
        "m_oth = df_clean[df_clean['lowest_voltage_module']!=hot_mod]['cell_spread_v'].dropna()*1000\n"
        "ax.hist(m_oth, bins=60, alpha=0.6, color='#1E88E5', label=f'Other module lowest (n={len(m_oth):,})')\n"
        "ax.hist(m_low, bins=60, alpha=0.6, color=MODULE_COLORS[hot_mod], label=f'Module {hot_mod} lowest (n={len(m_low):,})')\n"
        "ax.axvline(m_low.mean(), color='#B71C1C', linestyle='--', linewidth=2, label=f'M{hot_mod} mean: {m_low.mean():.0f}mV')\n"
        "ax.axvline(m_oth.mean(), color='#0D47A1', linestyle='--', linewidth=2, label=f'Others mean: {m_oth.mean():.0f}mV')\n"
        "ax.set_title(f'Cell Spread: Module {hot_mod} as Weakest vs Others')\n"
        "ax.set_xlabel('Cell Spread (mV)'); ax.set_ylabel('Count'); ax.legend(fontsize=9); ax.set_xlim(0, 200)\n\n"
        "ax = axes[1, 1]\n"
        "daily_temps = df_clean.groupby('date')[[f'module_{i}_temp_mean' for i in range(1, 6)]].mean().reset_index()\n"
        "dates_t = pd.to_datetime(daily_temps['date'])\n"
        "for i in range(1, 6):\n"
        "    lw = 3 if i == hot_mod else 1.5; alpha = 1.0 if i == hot_mod else 0.6\n"
        "    ls = '-' if i == hot_mod else '--'\n"
        "    label = f'Module {i}' + (' ← Hottest' if i == hot_mod else '')\n"
        "    ax.plot(dates_t, daily_temps[f'module_{i}_temp_mean'],\n"
        "            color=MODULE_COLORS[i], linewidth=lw, alpha=alpha, linestyle=ls, label=label)\n"
        "ax.set_title('Daily Mean Temperature per Module')\n"
        "ax.set_ylabel('Temperature (°C)'); ax.legend(fontsize=9); ax.tick_params(axis='x', rotation=45)\n\n"
        "plt.tight_layout()\n"
        "plt.savefig(f'outputs/ev02/04_module{hot_mod}_analysis.png', dpi=150, bbox_inches='tight')\n"
        "plt.show()"
    ),

    md_cell(
        "---\n## Section 6 — Degraded Cells: Worst Cell Analysis\n\n"
        "**What this does:** Tracks which specific cell positions are chronically the weakest across the pack.\n"
        "**What to look for:** Persistent worst-cell patterns repeating across multiple days and modules."
    ),

    code_cell(
        "print('=== WORST CELL ID FREQUENCY (top 20) ===')\n"
        "print(df_clean['worst_cell_id'].value_counts().head(20).to_string())\n"
        "print()\n"
        "print('=== LOWEST CELL per MODULE (top 5 each) ===')\n"
        "for i in range(1, 6):\n"
        "    col = f'module_{i}_lowest_cell'\n"
        "    if col in df_clean.columns:\n"
        "        print(f'Module {i}: {dict(df_clean[col].value_counts().head(5))}')"
    ),

    code_cell(
        "# Identify top 2 worst cell positions dynamically\n"
        "top_cells = df_clean['worst_cell_id'].value_counts().head(2).index.tolist()\n"
        "c1 = top_cells[0] if len(top_cells) > 0 else 'C1'\n"
        "c2 = top_cells[1] if len(top_cells) > 1 else 'C2'\n"
        "c1_pos = c1.split('_')[-1] if '_' in str(c1) else str(c1)\n"
        "c2_pos = c2.split('_')[-1] if '_' in str(c2) else str(c2)\n\n"
        "df_clean['is_c1_worst'] = df_clean['worst_cell_id'].astype(str).str.contains(c1_pos, na=False)\n"
        "df_clean['is_c2_worst'] = df_clean['worst_cell_id'].astype(str).str.contains(c2_pos, na=False)\n"
        "df_clean['is_hot_mod_worst'] = df_clean['worst_cell_id'].astype(str).str.startswith(f'M{hot_mod}', na=False)\n\n"
        "daily_cells = df_clean.groupby('date').agg(\n"
        "    pct_c1_worst=('is_c1_worst', 'mean'),\n"
        "    pct_c2_worst=('is_c2_worst', 'mean'),\n"
        "    pct_hot_mod_worst=('is_hot_mod_worst', 'mean'),\n"
        "    mean_spread=('cell_spread_v', 'mean'),\n"
        "    n=('cell_spread_v', 'count')\n"
        ").reset_index()\n\n"
        "print(f'=== WORST CELL POSITIONS: {c1_pos} and {c2_pos} ===')\n"
        "print(f'% time {c1_pos} is worst cell in pack: {df_clean[\"is_c1_worst\"].mean()*100:.1f}%')\n"
        "print(f'% time {c2_pos} is worst cell in pack: {df_clean[\"is_c2_worst\"].mean()*100:.1f}%')\n"
        "print(f'% time a Module {hot_mod} cell is worst: {df_clean[\"is_hot_mod_worst\"].mean()*100:.1f}%')"
    ),

    code_cell(
        "fig, axes = plt.subplots(2, 2, figsize=(16, 12))\n"
        "fig.suptitle(f'EV02 Cell Degradation — {c1_pos} and {c2_pos} Analysis')\n"
        "dates_c = pd.to_datetime(daily_cells['date'])\n\n"
        "ax = axes[0, 0]\n"
        "ax.plot(dates_c, daily_cells['pct_c1_worst']*100, color='#E53935', linewidth=2, marker='o', markersize=4, label=f'{c1_pos} is worst cell')\n"
        "ax.plot(dates_c, daily_cells['pct_c2_worst']*100, color='#FF7043', linewidth=2, marker='s', markersize=4, label=f'{c2_pos} is worst cell')\n"
        "ax.plot(dates_c, daily_cells['pct_hot_mod_worst']*100, color='#1E88E5', linewidth=1.5, linestyle='--', marker='^', markersize=3, label=f'Any M{hot_mod} cell is worst')\n"
        "ax.set_title(f'% Time {c1_pos} / {c2_pos} is the Worst Cell in the Pack')\n"
        "ax.set_ylabel('% of rows'); ax.legend(); ax.tick_params(axis='x', rotation=45)\n\n"
        "ax = axes[0, 1]\n"
        "daily_mod_v = df_clean.groupby('date')[[f'module_{i}_voltage_mean' for i in range(1, 6)]].mean().reset_index()\n"
        "dates_v = pd.to_datetime(daily_mod_v['date'])\n"
        "for i in range(1, 6):\n"
        "    if i != hot_mod:\n"
        "        ax.plot(dates_v, daily_mod_v[f'module_{i}_voltage_mean'], color=MODULE_COLORS[i], linewidth=1.5, alpha=0.5, linestyle='--', label=f'Module {i}')\n"
        "ax.plot(dates_v, daily_mod_v[f'module_{hot_mod}_voltage_mean'], color=MODULE_COLORS[hot_mod], linewidth=3, label=f'Module {hot_mod}')\n"
        "others_mean = daily_mod_v[[f'module_{i}_voltage_mean' for i in range(1, 6) if i != hot_mod]].mean(axis=1)\n"
        "ax.fill_between(dates_v, daily_mod_v[f'module_{hot_mod}_voltage_mean'], others_mean, alpha=0.15, color=MODULE_COLORS[hot_mod], label='Voltage gap')\n"
        "ax.set_title('Daily Mean Voltage per Module'); ax.set_ylabel('Mean Cell Voltage (V)')\n"
        "ax.legend(fontsize=8); ax.tick_params(axis='x', rotation=45)\n\n"
        "ax = axes[1, 0]\n"
        "daily_mod_r = df_clean.groupby('date')[[f'module_{i}_voltage_range' for i in range(1, 6)]].mean().reset_index()\n"
        "dates_r = pd.to_datetime(daily_mod_r['date'])\n"
        "for i in range(1, 6):\n"
        "    if i != hot_mod:\n"
        "        ax.plot(dates_r, daily_mod_r[f'module_{i}_voltage_range']*1000, color=MODULE_COLORS[i], linewidth=1.5, alpha=0.5, linestyle='--', label=f'Module {i}')\n"
        "ax.plot(dates_r, daily_mod_r[f'module_{hot_mod}_voltage_range']*1000, color=MODULE_COLORS[hot_mod], linewidth=3, label=f'Module {hot_mod}')\n"
        "ax.set_title('Daily Voltage Range within Each Module'); ax.set_ylabel('Voltage Range (mV)')\n"
        "ax.legend(fontsize=8); ax.tick_params(axis='x', rotation=45)\n\n"
        "ax = axes[1, 1]\n"
        "c1_total = int(df_clean['is_c1_worst'].sum())\n"
        "c2_total = int(df_clean['is_c2_worst'].sum())\n"
        "other_total = len(df_clean) - c1_total - c2_total\n"
        "ax.pie([c1_total, c2_total, other_total],\n"
        "       labels=[f'{c1_pos}\\n{c1_total/len(df_clean)*100:.0f}%', f'{c2_pos}\\n{c2_total/len(df_clean)*100:.0f}%', f'Other cells\\n{other_total/len(df_clean)*100:.0f}%'],\n"
        "       colors=['#E53935', '#FF7043', '#90A4AE'], explode=[0.05, 0.05, 0],\n"
        "       autopct='', startangle=90, textprops={'fontsize': 10})\n"
        "ax.set_title('Which Cell is the \"Worst Cell\" in the Pack?')\n\n"
        "plt.tight_layout()\n"
        "plt.savefig('outputs/ev02/05_cell_degradation.png', dpi=150, bbox_inches='tight')\n"
        "plt.show()"
    ),

    md_cell(
        "---\n## Section 7 — When Does Imbalance Get Worse?\n\n"
        "**What this does:** Tests whether cell imbalance is driven by operating conditions or is structural.\n"
        "**What to look for:** If correlation with current is near zero, imbalance is structural (cell degradation)."
    ),

    code_cell(
        "spread_by_soc = df_clean.groupby(['soc_band', 'current_direction'], observed=False)['cell_spread_v'].agg(\n"
        "    mean='mean', p95=lambda x: x.quantile(0.95), n='size'\n"
        ").reset_index()\n\n"
        "corr_signals = ['cell_spread_v', 'pack_voltage_std', 'pack_temp_range', 'abs_current_a', 'soc_pct']\n"
        "corr_matrix = df_clean[corr_signals].dropna().corr()\n"
        "spread_cur_corr = corr_matrix.loc['cell_spread_v', 'abs_current_a']\n"
        "spread_soc_corr = corr_matrix.loc['cell_spread_v', 'soc_pct']\n\n"
        "print('=== CELL SPREAD BY SOC AND CURRENT DIRECTION ===')\n"
        "print(spread_by_soc.round(4).to_string(index=False))\n"
        "print('\\n=== CORRELATION MATRIX ===')\n"
        "print(corr_matrix.round(3).to_string())\n"
        "print(f'\\nKey correlation — cell_spread vs abs_current: {spread_cur_corr:.3f}')\n"
        "print(f'Key correlation — cell_spread vs soc_pct:    {spread_soc_corr:.3f}')\n"
        "if abs(spread_cur_corr) < 0.05:\n"
        "    print('→ Near-zero correlation with current: imbalance is structural (cell degradation).')\n"
        "else:\n"
        "    print(f'→ Current has moderate influence on spread (r={spread_cur_corr:.2f}) — monitor heavy load.')"
    ),

    code_cell(
        "fig, axes = plt.subplots(2, 2, figsize=(16, 12))\n"
        "fig.suptitle('When Does Imbalance Occur? — Condition Analysis')\n\n"
        "ax = axes[0, 0]\n"
        "soc_discharge = spread_by_soc[spread_by_soc['current_direction'] == 'discharge']\n"
        "soc_charge = spread_by_soc[spread_by_soc['current_direction'] == 'charge']\n"
        "x_labels = ['0-20%', '20-40%', '40-60%', '60-80%', '80-100%']\n"
        "x = np.arange(len(x_labels)); width = 0.35\n"
        "if len(soc_discharge) == 5: ax.bar(x - width/2, soc_discharge['mean']*1000, width, color='#FF5722', alpha=0.85, label='Discharge')\n"
        "if len(soc_charge) == 5: ax.bar(x + width/2, soc_charge['mean']*1000, width, color='#2196F3', alpha=0.85, label='Charging/Regen')\n"
        "ax.set_xticks(x); ax.set_xticklabels(x_labels)\n"
        "ax.set_title('Mean Cell Spread by SOC Band and Current Direction')\n"
        "ax.set_xlabel('SOC Band'); ax.set_ylabel('Cell Spread (mV)')\n"
        "ax.axhline(90, color='#FF9800', linestyle='--', linewidth=1.5, label='Warn threshold'); ax.legend()\n\n"
        "ax = axes[0, 1]\n"
        "sample = df_clean.sample(min(80000, len(df_clean)), random_state=42)\n"
        "ax.scatter(sample['soc_pct'], sample['cell_spread_v']*1000, s=3, alpha=0.15, color='#1E88E5')\n"
        "soc_bins = pd.cut(sample['soc_pct'], bins=20)\n"
        "soc_mean_spread = sample.groupby(soc_bins, observed=False)['cell_spread_v'].mean()*1000\n"
        "ax.plot([i.mid for i in soc_mean_spread.index], soc_mean_spread.values, color='#E53935', linewidth=3, label='Binned mean')\n"
        "ax.axhline(90, color='#FF9800', linestyle='--', linewidth=1.5, label='Warn (90mV)')\n"
        "ax.set_title('Cell Spread vs SOC'); ax.set_xlabel('SOC (%)'); ax.set_ylabel('Cell Spread (mV)')\n"
        "ax.set_ylim(0, 250); ax.legend()\n\n"
        "ax = axes[1, 0]\n"
        "ax.scatter(sample['abs_current_a'], sample['cell_spread_v']*1000, s=3, alpha=0.15, color='#FF5722')\n"
        "cur_bins = pd.cut(sample['abs_current_a'], bins=20)\n"
        "cur_mean_spread = sample.groupby(cur_bins, observed=False)['cell_spread_v'].mean()*1000\n"
        "ax.plot([i.mid for i in cur_mean_spread.index], cur_mean_spread.values, color='#1E88E5', linewidth=3, label='Binned mean')\n"
        "ax.axhline(90, color='#FF9800', linestyle='--', linewidth=1.5, label='Warn (90mV)')\n"
        "ax.set_title('Cell Spread vs Current'); ax.set_xlabel('Absolute Current (A)'); ax.set_ylabel('Cell Spread (mV)')\n"
        "ax.set_ylim(0, 250); ax.legend()\n\n"
        "ax = axes[1, 1]\n"
        "corr_display = corr_matrix.copy()\n"
        "corr_display.index = ['Cell Spread', 'Pack V Std', 'Temp Range', 'Current', 'SOC']\n"
        "corr_display.columns = ['Cell Spread', 'Pack V Std', 'Temp Range', 'Current', 'SOC']\n"
        "im = ax.imshow(corr_display.values, cmap='RdBu_r', vmin=-1, vmax=1, aspect='auto')\n"
        "ax.set_xticks(range(len(corr_display.columns))); ax.set_yticks(range(len(corr_display.index)))\n"
        "ax.set_xticklabels(corr_display.columns, rotation=30, ha='right', fontsize=9)\n"
        "ax.set_yticklabels(corr_display.index, fontsize=9)\n"
        "for i in range(len(corr_display)):\n"
        "    for j in range(len(corr_display.columns)):\n"
        "        val = corr_display.values[i, j]\n"
        "        ax.text(j, i, f'{val:.2f}', ha='center', va='center', color='white' if abs(val) > 0.5 else 'black', fontsize=9)\n"
        "plt.colorbar(im, ax=ax); ax.set_title('Correlation Matrix')\n\n"
        "plt.tight_layout()\n"
        "plt.savefig('outputs/ev02/06_imbalance_conditions.png', dpi=150, bbox_inches='tight')\n"
        "plt.show()"
    ),

    md_cell(
        "---\n## Section 8 — The Worst Operating Condition\n\n"
        "**What this does:** Identifies the highest-stress scenario for the battery.\n"
        "**What to look for:** Does the worst combination push spread above the warn threshold?"
    ),

    code_cell(
        "work_threshold = df_clean['abs_current_a'].quantile(0.70)\n"
        "working = df_clean[\n"
        "    (df_clean['abs_current_a'] >= work_threshold) &\n"
        "    (df_clean['current_direction'] == 'discharge')\n"
        "].copy()\n"
        "low_soc_work = working[working['soc_pct'] <= 20].copy()\n"
        "m_hot_low_logsoc = low_soc_work[low_soc_work['lowest_voltage_module'] == hot_mod]\n"
        "normal = df_clean[(df_clean['soc_pct'] >= 80) & (df_clean['abs_current_a'] < 50)]\n\n"
        "print('=== CONDITION COMPARISON ===')\n"
        "for label, subset in [('Normal (SOC>80%, current<50A)', normal), ('Working load (top 30% current)', working),\n"
        "                       ('Low SOC + working load', low_soc_work), (f'Worst case (M{hot_mod}+low SOC+load)', m_hot_low_logsoc)]:\n"
        "    if len(subset) > 0:\n"
        "        print(f'{label}:')\n"
        "        print(f\"  Mean spread: {subset['cell_spread_v'].mean()*1000:.1f} mV  p95: {subset['cell_spread_v'].quantile(0.95)*1000:.1f} mV  n={len(subset):,}\")\n"
        "    else:\n"
        "        print(f'{label}: No data')"
    ),

    code_cell(
        "fig, axes = plt.subplots(1, 2, figsize=(16, 7))\n"
        "fig.suptitle(f'Worst Operating Condition — Module {hot_mod} + Low SOC + Heavy Work')\n\n"
        "conditions = ['Normal\\n(SOC>80%, low current)', 'Working load\\n(top 30% current)',\n"
        "              'Low SOC\\n+ working load', f'WORST CASE\\n(M{hot_mod} weakest +\\nlow SOC + load)']\n"
        "means = [\n"
        "    normal['cell_spread_v'].mean()*1000 if len(normal) > 0 else 0,\n"
        "    working['cell_spread_v'].mean()*1000 if len(working) > 0 else 0,\n"
        "    low_soc_work['cell_spread_v'].mean()*1000 if len(low_soc_work) > 0 else 0,\n"
        "    m_hot_low_logsoc['cell_spread_v'].mean()*1000 if len(m_hot_low_logsoc) > 0 else 0,\n"
        "]\n"
        "p95s = [\n"
        "    normal['cell_spread_v'].quantile(0.95)*1000 if len(normal) > 0 else 0,\n"
        "    working['cell_spread_v'].quantile(0.95)*1000 if len(working) > 0 else 0,\n"
        "    low_soc_work['cell_spread_v'].quantile(0.95)*1000 if len(low_soc_work) > 0 else 0,\n"
        "    m_hot_low_logsoc['cell_spread_v'].quantile(0.95)*1000 if len(m_hot_low_logsoc) > 0 else 0,\n"
        "]\n"
        "ax = axes[0]\n"
        "bar_colors = ['#43A047', '#1E88E5', '#FB8C00', '#E53935']\n"
        "x = np.arange(len(conditions))\n"
        "bars = ax.bar(x, means, color=bar_colors, alpha=0.85, edgecolor='white', linewidth=1.5, label='Mean spread')\n"
        "ax.scatter(x, p95s, color='black', s=60, zorder=5, marker='D', label='p95 spread')\n"
        "ax.axhline(90, color='#FF9800', linestyle='--', linewidth=2, label='Warn (90mV)')\n"
        "ax.axhline(130, color='#E53935', linestyle='--', linewidth=2, label='Alert (130mV)')\n"
        "ax.set_xticks(x); ax.set_xticklabels(conditions, fontsize=9)\n"
        "ax.set_ylabel('Cell Spread (mV)'); ax.set_title('Mean Cell Spread Under Different Operating Conditions'); ax.legend(fontsize=9)\n"
        "for bar, val in zip(bars, means):\n"
        "    ax.text(bar.get_x()+bar.get_width()/2, bar.get_height()+1,\n"
        "            f'{val:.0f}mV', ha='center', va='bottom', fontweight='bold', fontsize=10)\n\n"
        "ax = axes[1]\n"
        "if len(normal) > 0: ax.hist(normal['cell_spread_v']*1000, bins=50, alpha=0.6, color='#43A047', density=True, label=f'Normal ({means[0]:.0f}mV)')\n"
        "if len(working) > 0: ax.hist(working['cell_spread_v']*1000, bins=50, alpha=0.5, color='#1E88E5', density=True, label=f'Working load ({means[1]:.0f}mV)')\n"
        "if len(low_soc_work) > 0: ax.hist(low_soc_work['cell_spread_v']*1000, bins=40, alpha=0.6, color='#FB8C00', density=True, label=f'Low SOC work ({means[2]:.0f}mV)')\n"
        "if len(m_hot_low_logsoc) > 50: ax.hist(m_hot_low_logsoc['cell_spread_v']*1000, bins=30, alpha=0.7, color='#E53935', density=True, label=f'Worst case ({means[3]:.0f}mV)')\n"
        "ax.axvline(90, color='#FF9800', linestyle='--', linewidth=2, label='Warn (90mV)')\n"
        "ax.axvline(130, color='#E53935', linestyle='--', linewidth=2, label='Alert (130mV)')\n"
        "ax.set_title('Spread Distribution by Operating Condition')\n"
        "ax.set_xlabel('Cell Spread (mV)'); ax.set_ylabel('Density'); ax.set_xlim(0, 200); ax.legend(fontsize=9)\n\n"
        "plt.tight_layout()\n"
        "plt.savefig('outputs/ev02/07_worst_conditions.png', dpi=150, bbox_inches='tight')\n"
        "plt.show()"
    ),

    md_cell(
        "---\n## Section 9 — Trip-Level Analysis\n\n"
        "**What this does:** Ranks all work sessions by battery stress.\n"
        "**What to look for:** Are there specific trips that are systematically harder on the pack?"
    ),

    code_cell(
        "trip_features = df_clean.assign(\n"
        "    mod_hot=(df_clean['hottest_module'] == hot_mod),\n"
        "    mod_low=(df_clean['lowest_voltage_module'] == hot_mod),\n"
        "    low_soc=(df_clean['soc_pct'] <= 20),\n"
        "    high_load=(df_clean['abs_current_a'] >= work_threshold),\n"
        "    above_warn=(df_clean['cell_spread_v'] > 0.09),\n"
        ").groupby('trip_id').agg(\n"
        "    n=('cell_spread_v', 'size'),\n"
        "    mean_spread=('cell_spread_v', 'mean'),\n"
        "    p95_spread=('cell_spread_v', lambda x: x.quantile(0.95)),\n"
        "    max_spread=('cell_spread_v', 'max'),\n"
        "    mean_temp_range=('pack_temp_range', 'mean'),\n"
        "    mean_abs_current=('abs_current_a', 'mean'),\n"
        "    pct_low_soc=('low_soc', 'mean'),\n"
        "    pct_high_load=('high_load', 'mean'),\n"
        "    pct_mod_hot=('mod_hot', 'mean'),\n"
        "    pct_mod_low=('mod_low', 'mean'),\n"
        "    pct_above_warn=('above_warn', 'mean'),\n"
        ")\n"
        "for col in ['pct_low_soc', 'pct_high_load', 'pct_mod_hot', 'pct_mod_low', 'pct_above_warn']:\n"
        "    trip_features[col] *= 100\n\n"
        "top_trips = trip_features.sort_values('p95_spread', ascending=False).head(15)\n"
        "print('=== TOP 15 MOST STRESSED TRIPS (by p95 cell spread) ===')\n"
        "print(top_trips[['n', 'mean_spread', 'p95_spread', 'max_spread', 'mean_abs_current', 'pct_low_soc', 'pct_mod_hot', 'pct_mod_low']].round(3).to_string())\n"
        "print(f'\\nTotal trips analysed: {len(trip_features):,}')\n"
        "print(f'Trips with mean spread > 90mV: {(trip_features[\"mean_spread\"] > 0.09).sum()}')\n"
        "print(f'Trips with max spread > 130mV: {(trip_features[\"max_spread\"] > 0.13).sum()}')"
    ),

    code_cell(
        "fig, axes = plt.subplots(1, 2, figsize=(16, 7))\n"
        "fig.suptitle('Trip-Level Battery Stress Analysis — EV02')\n\n"
        "ax = axes[0]\n"
        "trip_means = trip_features[trip_features['n'] >= 60]['mean_spread'] * 1000\n"
        "ax.hist(trip_means, bins=50, color='#2196F3', alpha=0.8, edgecolor='white')\n"
        "ax.axvline(trip_means.mean(), color='#1565C0', linestyle='--', linewidth=2, label=f'Mean: {trip_means.mean():.0f}mV')\n"
        "ax.axvline(90, color='#FF9800', linestyle='--', linewidth=2, label='Warn threshold (90mV)')\n"
        "ax.axvline(130, color='#E53935', linestyle='--', linewidth=2, label='Alert threshold (130mV)')\n"
        "ax.set_title('Distribution of Mean Cell Spread per Trip (≥60 rows)')\n"
        "ax.set_xlabel('Mean Cell Spread per Trip (mV)'); ax.set_ylabel('Number of Trips'); ax.legend()\n\n"
        "ax = axes[1]\n"
        "plot_trips = trip_features[trip_features['n'] >= 60].copy()\n"
        "sc = ax.scatter(plot_trips['pct_mod_low'], plot_trips['mean_spread']*1000,\n"
        "    c=plot_trips['mean_abs_current'], cmap='YlOrRd',\n"
        "    s=plot_trips['n']/50, alpha=0.7, edgecolors='gray', linewidth=0.5)\n"
        "plt.colorbar(sc, ax=ax, label='Mean Current (A)')\n"
        "ax.axhline(90, color='#FF9800', linestyle='--', linewidth=1.5, label='Warn (90mV)')\n"
        "ax.set_title(f'Trip Mean Spread vs % Time Module {hot_mod} is Weakest\\n(dot size = trip length, color = current)')\n"
        "ax.set_xlabel(f'% Time Module {hot_mod} is Lowest Voltage Module')\n"
        "ax.set_ylabel('Mean Cell Spread (mV)'); ax.legend()\n\n"
        "plt.tight_layout()\n"
        "plt.savefig('outputs/ev02/08_trip_analysis.png', dpi=150, bbox_inches='tight')\n"
        "plt.show()"
    ),

    md_cell(
        "---\n## Section 10 — Summary Dashboard\n\n"
        "**What this does:** Consolidates all findings into a single executive summary page."
    ),

    code_cell(
        "fig = plt.figure(figsize=(20, 14))\n"
        "fig.patch.set_facecolor('white')\n"
        "gs = gridspec.GridSpec(3, 4, figure=fig, hspace=0.45, wspace=0.35)\n"
        "fig.suptitle(f'EV02 Battery Health Report — Executive Summary\\n{df_clean[\"date\"].min()} – {df_clean[\"date\"].max()}',\n"
        "             fontsize=16, fontweight='bold', y=0.98)\n\n"
        "metrics = [\n"
        "    (f'{len(df_clean):,}', 'Total clean rows\\n(1Hz telemetry)'),\n"
        "    (f'{df_clean[\"date\"].nunique()}', 'Operating days\\nanalyzed'),\n"
        "    (f\"{daily['active_hours'].mean():.1f}h\", 'Avg active hours\\nper day'),\n"
        "    (f\"{df_clean['cell_spread_v'].mean()*1000:.0f}mV\", 'Mean cell spread\\n(healthy < 90mV)'),\n"
        "]\n"
        "metric_colors = ['#1E88E5', '#43A047', '#FB8C00', '#8E24AA']\n"
        "for idx, (val, label) in enumerate(metrics):\n"
        "    ax = fig.add_subplot(gs[0, idx])\n"
        "    ax.set_facecolor(metric_colors[idx])\n"
        "    ax.text(0.5, 0.6, val, transform=ax.transAxes, ha='center', va='center', fontsize=22, fontweight='bold', color='white')\n"
        "    ax.text(0.5, 0.2, label, transform=ax.transAxes, ha='center', va='center', fontsize=10, color='white', alpha=0.9)\n"
        "    ax.set_xticks([]); ax.set_yticks([])\n"
        "    for spine in ax.spines.values(): spine.set_visible(False)\n\n"
        "ax = fig.add_subplot(gs[1, :2])\n"
        "hot_pct = [(df_clean['hottest_module'] == i).mean()*100 for i in range(1, 6)]\n"
        "bars = ax.bar([f'Module {i}' for i in range(1, 6)], hot_pct, color=[MODULE_COLORS[i] for i in range(1, 6)], edgecolor='white', linewidth=1.5)\n"
        "ax.axhline(20, color='gray', linestyle=':', linewidth=1.5, label='Expected if uniform (20%)')\n"
        "ax.set_title(f'% Time Each Module is Hottest → Module {hot_mod} runs hot {max(hot_pct):.0f}% of all operating hours')\n"
        "ax.set_ylabel('% of operating hours'); ax.legend(fontsize=9)\n"
        "for bar, val in zip(bars, hot_pct):\n"
        "    ax.text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.5, f'{val:.0f}%', ha='center', va='bottom', fontweight='bold', fontsize=11)\n\n"
        "ax = fig.add_subplot(gs[1, 2:])\n"
        "ax.fill_between(pd.to_datetime(daily_health['date']), daily_health['mean_spread']*1000, daily_health['p95_spread']*1000, alpha=0.2, color='#1E88E5', label='Mean–p95 band')\n"
        "ax.plot(pd.to_datetime(daily_health['date']), daily_health['mean_spread']*1000, color='#1565C0', linewidth=2, marker='o', markersize=3, label='Mean spread')\n"
        "ax.axhline(90, color='#FF9800', linestyle='--', linewidth=2, label='Warn (90mV)')\n"
        "ax.axhline(130, color='#E53935', linestyle='--', linewidth=2, label='Alert (130mV)')\n"
        "ax.set_title('Daily Cell Voltage Spread Trend'); ax.set_ylabel('Cell Spread (mV)')\n"
        "ax.legend(fontsize=8); ax.tick_params(axis='x', rotation=30)\n\n"
        "ax = fig.add_subplot(gs[2, :2])\n"
        "ax.plot(pd.to_datetime(daily_cells['date']), daily_cells['pct_c1_worst']*100, color='#E53935', linewidth=2, marker='o', markersize=4, label=f'{c1_pos} is worst cell')\n"
        "ax.plot(pd.to_datetime(daily_cells['date']), daily_cells['pct_c2_worst']*100, color='#FF7043', linewidth=2, marker='s', markersize=4, label=f'{c2_pos} is worst cell')\n"
        "ax.set_title(f'% Time {c1_pos} / {c2_pos} are the Weakest Cell in Pack')\n"
        "ax.set_ylabel('% of operating hours'); ax.legend(); ax.tick_params(axis='x', rotation=30)\n\n"
        "ax = fig.add_subplot(gs[2, 2:])\n"
        "cond_labels = ['Normal\\nops', 'Working\\nload', 'Low SOC +\\nload', f'WORST\\n(M{hot_mod}+\\nlow SOC+load)']\n"
        "bars2 = ax.bar(range(len(cond_labels)), means, color=['#43A047','#1E88E5','#FB8C00','#E53935'], edgecolor='white', linewidth=1.5)\n"
        "ax.set_xticks(range(len(cond_labels))); ax.set_xticklabels(cond_labels, fontsize=9)\n"
        "ax.axhline(90, color='#FF9800', linestyle='--', linewidth=2, label='Warn (90mV)')\n"
        "ax.axhline(130, color='#E53935', linestyle='--', linewidth=2, label='Alert (130mV)')\n"
        "ax.set_title('Mean Cell Spread by Operating Condition'); ax.set_ylabel('Cell Spread (mV)'); ax.legend(fontsize=9)\n"
        "for bar, val in zip(bars2, means):\n"
        "    ax.text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.5, f'{val:.0f}mV', ha='center', va='bottom', fontweight='bold', fontsize=11)\n\n"
        "plt.savefig('outputs/ev02/09_executive_summary.png', dpi=150, bbox_inches='tight')\n"
        "plt.show()\n"
        "print('Dashboard saved to outputs/ev02/09_executive_summary.png')"
    ),

    md_cell(
        "---\n## Section 11 — Findings Summary\n\n"
        "**Run this cell to print the computed findings derived from EV02 data.**"
    ),

    code_cell(
        "print('=' * 70)\n"
        "print('EV02 BATTERY HEALTH DIAGNOSTIC — KEY FINDINGS')\n"
        "print(f'Electrified Excavator | {df_clean[\"date\"].min()} – {df_clean[\"date\"].max()}')\n"
        "print('=' * 70)\n\n"
        "mean_spread_mv = df_clean['cell_spread_v'].mean() * 1000\n"
        "p95_spread_mv = df_clean['cell_spread_v'].quantile(0.95) * 1000\n"
        "pct_above_warn = (df_clean['cell_spread_v'] > 0.09).mean() * 100\n"
        "pct_above_alert = (df_clean['cell_spread_v'] > 0.13).mean() * 100\n"
        "hot_mod_pct = (df_clean['hottest_module'] == hot_mod).mean() * 100\n"
        "c1_pct = df_clean['is_c1_worst'].mean() * 100\n"
        "c2_pct = df_clean['is_c2_worst'].mean() * 100\n\n"
        "print(f\"\"\"\n"
        "OPERATING PROFILE\n"
        "──────────────────\n"
        "Total operating days:      {df_clean['date'].nunique()}\n"
        "Average active hours/day:  {daily['active_hours'].mean():.1f}h\n"
        "Median SOC (operating):    {df_clean['soc_pct'].median():.0f}%\n"
        "Total trips:               {df_clean['trip_id'].nunique():,}\n\n"
        "PACK HEALTH\n"
        "────────────\n"
        "Mean cell spread:          {mean_spread_mv:.1f} mV  (warn: 90mV, alert: 130mV)\n"
        "p95 cell spread:           {p95_spread_mv:.1f} mV\n"
        "% time above warn (90mV):  {pct_above_warn:.1f}%\n"
        "% time above alert (130mV):{pct_above_alert:.1f}%\n"
        "Mean pack temp range:      {df_clean['pack_temp_range'].mean():.1f}°C\n\n"
        "THERMAL DOMINANCE\n"
        "──────────────────\n"
        "Module {hot_mod} is hottest: {hot_mod_pct:.1f}% of all operating hours\n\n"
        "CELL DEGRADATION\n"
        "─────────────────\n"
        "{c1_pos} is worst cell: {c1_pct:.1f}% of operating hours\n"
        "{c2_pos} is worst cell: {c2_pct:.1f}% of operating hours\n"
        "Imbalance vs current corr:  {spread_cur_corr:.3f}\n\n"
        "WORST OPERATING CONDITION\n"
        "──────────────────────────\n"
        "Normal spread:             {means[0]:.0f} mV\n"
        "Working load spread:       {means[1]:.0f} mV\n"
        "Low SOC + working load:    {means[2]:.0f} mV\n"
        "Worst case (M{hot_mod}+low SOC+load): {means[3]:.0f} mV\n"
        "\"\"\")\n\n"
        "if mean_spread_mv < 60:\n"
        "    print('Pack health:    HEALTHY — mean spread well within thresholds')\n"
        "elif mean_spread_mv < 90:\n"
        "    print('Pack health:    MONITOR — mean spread approaching warn threshold')\n"
        "else:\n"
        "    print('Pack health:    DEGRADED — mean spread above warn threshold')\n\n"
        "if pct_above_warn < 5:\n"
        "    print(f'Warn breaches:  LOW ({pct_above_warn:.1f}% of time above 90mV)')\n"
        "else:\n"
        "    print(f'Warn breaches:  ELEVATED ({pct_above_warn:.1f}% of time above 90mV)')\n\n"
        "print(f'Module {hot_mod}:       MONITOR — consistently hottest ({hot_mod_pct:.0f}% of time)')\n"
        "print(f'Cells {c1_pos}/{c2_pos}: WATCH — chronically weakest cell positions')\n"
        "print('=' * 70)"
    ),
]

nb = {
    "nbformat": 4,
    "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.11.0"},
    },
    "cells": cells,
}

out = Path("notebooks/ev02_excavator_battery_diagnostic_report.ipynb")
out.write_text(json.dumps(nb, indent=1))
print(f"Written: {out}  ({len(cells)} cells)")
