"""
Email Report Sender
====================
Sends daily PDF reports as email attachments via Gmail SMTP.

Setup (one-time):
    1. Enable 2-Step Verification on your Google account
    2. Go to myaccount.google.com → Security → App Passwords
    3. Create an app password for "Mail"
    4. Set environment variables on the VPS:
         export EMAIL_SENDER=your@gmail.com
         export EMAIL_PASSWORD=your_16_char_app_password
         export EMAIL_RECIPIENTS=you@gmail.com,colleague@gmail.com

Usage:
    python scripts/send_report_email.py --date 2026-05-31
    python scripts/send_report_email.py --date 2026-05-31 --subject "Custom subject"
"""

from __future__ import annotations

import argparse
import os
import smtplib
import sys
from datetime import date, timedelta
from email import encoders
from email.mime.base import MIMEBase
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT))

from configs.settings import MACHINE_TYPES

PDF_DIR = PROJECT_ROOT / "reports" / "daily_pdf"

SMTP_HOST = "smtp.gmail.com"
SMTP_PORT = 587


def build_body(dt: str, vehicles: list[str], attached: list[str]) -> str:
    lines = [
        f"Daily Battery Intelligence Report — {dt}",
        "",
        "Please find the daily battery reports attached.",
        "",
        "Summary:",
    ]
    for vid in vehicles:
        machine = MACHINE_TYPES.get(vid, "Unknown")
        lines.append(f"  • {vid} ({machine})")
    lines += [
        "",
        f"Reports attached: {len(attached)} PDF file(s)",
        "",
        "This is an automated report generated by the Battery Intelligence Platform.",
        "Do not reply to this email.",
    ]
    return "\n".join(lines)


def send_email(
    sender: str,
    password: str,
    recipients: list[str],
    subject: str,
    body: str,
    attachments: list[Path],
) -> None:
    msg = MIMEMultipart()
    msg["From"]    = sender
    msg["To"]      = ", ".join(recipients)
    msg["Subject"] = subject

    msg.attach(MIMEText(body, "plain"))

    for path in attachments:
        with open(path, "rb") as f:
            part = MIMEBase("application", "octet-stream")
            part.set_payload(f.read())
        encoders.encode_base64(part)
        part.add_header("Content-Disposition", f"attachment; filename={path.name}")
        msg.attach(part)

    with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
        server.ehlo()
        server.starttls()
        server.login(sender, password)
        server.sendmail(sender, recipients, msg.as_string())


def main() -> None:
    ap = argparse.ArgumentParser(description="Send daily PDF reports via email")
    ap.add_argument("--date",       default=None, help="YYYY-MM-DD (default: yesterday)")
    ap.add_argument("--subject",    default=None, help="Override email subject")
    ap.add_argument("--vehicle-id", default=None, dest="vehicle_id",
                    help="Send only this vehicle's report")
    args = ap.parse_args()

    dt = args.date or (date.today() - timedelta(days=1)).isoformat()

    sender     = os.getenv("EMAIL_SENDER", "")
    password   = os.getenv("EMAIL_PASSWORD", "")
    recipients = [r.strip() for r in os.getenv("EMAIL_RECIPIENTS", "").split(",") if r.strip()]

    if not sender or not password:
        print("ERROR: Set EMAIL_SENDER and EMAIL_PASSWORD environment variables.")
        print("       Use a Gmail App Password (not your regular password).")
        sys.exit(1)

    if not recipients:
        print("ERROR: Set EMAIL_RECIPIENTS environment variable (comma-separated emails).")
        sys.exit(1)

    vehicles = [args.vehicle_id] if args.vehicle_id else sorted(MACHINE_TYPES.keys())

    # Find PDF files for this date
    attachments: list[Path] = []
    for vid in vehicles:
        pdf = PDF_DIR / f"{vid}_{dt}.pdf"
        if pdf.exists():
            attachments.append(pdf)
        else:
            print(f"  ⚠  PDF not found for {vid} on {dt}: {pdf}")

    if not attachments:
        print(f"No PDF reports found for {dt}. Run generate_daily_report.py first.")
        sys.exit(1)

    subject = args.subject or f"Battery Intelligence Report — {dt} ({len(attachments)} vehicle(s))"

    print(f"\nSending report email for {dt}")
    print(f"  From    : {sender}")
    print(f"  To      : {', '.join(recipients)}")
    print(f"  Subject : {subject}")
    print(f"  Attach  : {[p.name for p in attachments]}")

    try:
        send_email(
            sender=sender,
            password=password,
            recipients=recipients,
            subject=subject,
            body=build_body(dt, vehicles, [p.name for p in attachments]),
            attachments=attachments,
        )
        print("\n  ✓ Email sent successfully.")
    except Exception as e:
        print(f"\n  ✗ Failed to send email: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
